In [57]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [58]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [59]:
df.shape

(569, 33)

In [60]:
df.drop(columns=['id' ,'Unnamed: 32'], inplace= True)

In [61]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [62]:
x= df.iloc[:,1:]
y= df.iloc[:,0]
y

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [63]:
x_train,x_test,y_train,y_test= train_test_split(x,y , test_size = 0.2)

In [64]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

x_train

array([[-0.85213743,  0.50666398, -0.87530059, ..., -1.0815175 ,
         0.13554485, -0.71681525],
       [ 0.35615587, -1.17828833,  0.44687451, ...,  1.89205557,
         2.84315158,  0.86800875],
       [-0.95620097,  0.64098885, -0.96582035, ..., -0.59981199,
         0.1179318 , -0.41422222],
       ...,
       [-0.59486924, -1.09109499, -0.57817789, ..., -0.74179314,
        -0.2311269 , -0.05548948],
       [ 1.52976133,  0.9991885 ,  1.56160851, ...,  0.63589369,
         0.0458784 , -0.44116928],
       [ 1.44304171,  1.65667339,  1.56160851, ...,  1.0556245 ,
        -0.92924431,  0.4508907 ]])

In [65]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)
y_train

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,

In [66]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)

y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [67]:
x_train_tensor.shape

torch.Size([455, 30])

## Defining the Model

In [41]:
class SimpleNN():
  def __init__(self, X):
   self.weights = torch.rand(X.shape[1], 1 , dtype = torch.float64, requires_grad = True)
   self.bias = torch.zeros(1, dtype = torch.float64, requires_grad = True)

  def forward(self, X):
    z= torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred


  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss




In [46]:
LR=0.1
epochs = 35
model = SimpleNN(x_train_tensor)

for epoch in range(epochs):
# Forward Pass
  y_pred = model.forward(x_train_tensor)

# loss
  loss = model.loss_function(y_pred,y_train_tensor)

#backward pass
  loss.backward()

#update weights

  with torch.no_grad():
      model.weights -= LR * model.weights.grad
      model.bias -= LR * model.bias.grad

# zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.3402580149903014
Epoch: 2, Loss: 3.193921926185041
Epoch: 3, Loss: 3.0435835121059935
Epoch: 4, Loss: 2.8902450012651553
Epoch: 5, Loss: 2.7358547199577106
Epoch: 6, Loss: 2.579396411723321
Epoch: 7, Loss: 2.4237025991111834
Epoch: 8, Loss: 2.2657810107138094
Epoch: 9, Loss: 2.1081176069344174
Epoch: 10, Loss: 1.9531961882515005
Epoch: 11, Loss: 1.8038911666968405
Epoch: 12, Loss: 1.661597062524537
Epoch: 13, Loss: 1.5300694419985852
Epoch: 14, Loss: 1.4037392687508117
Epoch: 15, Loss: 1.291933761512748
Epoch: 16, Loss: 1.1952954895353982
Epoch: 17, Loss: 1.1137221562280368
Epoch: 18, Loss: 1.0462723618191812
Epoch: 19, Loss: 0.9913016330740487
Epoch: 20, Loss: 0.9467956067905432
Epoch: 21, Loss: 0.9107290082674543
Epoch: 22, Loss: 0.8813040690120585
Epoch: 23, Loss: 0.8570454481848633
Epoch: 24, Loss: 0.8368013165771093
Epoch: 25, Loss: 0.8196999356351264
Epoch: 26, Loss: 0.8050915406240919
Epoch: 27, Loss: 0.7924921900137978
Epoch: 28, Loss: 0.7815375866091671
Epoch

In [47]:
model.bias

tensor([-0.2257], dtype=torch.float64, requires_grad=True)

## Evaluation

In [49]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6637426614761353


In [68]:
import torch.nn as nn
LR=0.1
epochs = 35

class mysimpleNN(nn.Module):

  def __init__(self, input_size):
    super().__init__()
    self.linear = nn.Linear(input_size, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    x = self.linear(x)
    x = self.sigmoid(x)
    return x

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

In [71]:
model = mysimpleNN(x_train_tensor.shape[1])

for epoch in range(epochs):
# Forward Pass
  y_pred = model(x_train_tensor.float())

# loss
  loss = model.loss_function(y_pred,y_train_tensor)

#backward pass
  loss.backward()

#update weights

  with torch.no_grad():
      model.linear.weight -= LR * model.linear.weight.grad
      model.linear.bias -= LR * model.linear.bias.grad


# zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.789408266544342
Epoch: 2, Loss: 0.7536143064498901
Epoch: 3, Loss: 0.7308108806610107
Epoch: 4, Loss: 0.7164425253868103
Epoch: 5, Loss: 0.7071452736854553
Epoch: 6, Loss: 0.7007883787155151
Epoch: 7, Loss: 0.6961454153060913
Epoch: 8, Loss: 0.6925399303436279
Epoch: 9, Loss: 0.6895993947982788
Epoch: 10, Loss: 0.6871123909950256
Epoch: 11, Loss: 0.6849526166915894
Epoch: 12, Loss: 0.6830403208732605
Epoch: 13, Loss: 0.6813218593597412
Epoch: 14, Loss: 0.6797597408294678
Epoch: 15, Loss: 0.6783266663551331
Epoch: 16, Loss: 0.6770023107528687
Epoch: 17, Loss: 0.6757710576057434
Epoch: 18, Loss: 0.6746208071708679
Epoch: 19, Loss: 0.6735419034957886
Epoch: 20, Loss: 0.6725267767906189
Epoch: 21, Loss: 0.6715693473815918
Epoch: 22, Loss: 0.6706641912460327
Epoch: 23, Loss: 0.6698070764541626
Epoch: 24, Loss: 0.6689945459365845
Epoch: 25, Loss: 0.6682232022285461
Epoch: 26, Loss: 0.6674903631210327
Epoch: 27, Loss: 0.6667934656143188
Epoch: 28, Loss: 0.6661306023597717
Ep

In [72]:
model.linear.weight

Parameter containing:
tensor([[-0.0422,  0.0042,  0.2404, -0.0984,  0.0894,  0.1527, -0.0063,  0.0652,
          0.0286,  0.0143, -0.0719,  0.0401, -0.0407, -0.0524, -0.0466,  0.0114,
         -0.0557, -0.0476, -0.0007,  0.0327,  0.0622,  0.0076, -0.0339, -0.0195,
         -0.0583, -0.1374,  0.0542, -0.0700, -0.0687,  0.0125]],
       requires_grad=True)

In [75]:
# model evaluation
with torch.no_grad():
  y_pred = model(x_test_tensor.float())
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5614035129547119


## Built in Loss *Function*

In [80]:
import torch.nn as nn
LR=0.1
epochs = 35
loss_func = nn.BCELoss() #Binary cross Entropy

class mysimpleNN(nn.Module):

  def __init__(self, input_size):
    super().__init__()
    self.linear = nn.Linear(input_size, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    x = self.linear(x)
    x = self.sigmoid(x)
    return x



In [83]:
model = mysimpleNN(x_train_tensor.shape[1])

for epoch in range(epochs):
# Forward Pass
  y_pred = model(x_train_tensor.float())

# loss
  loss = loss_func(y_pred, y_train_tensor.view(-1,1).float())

#backward pass
  loss.backward()

#update weights

  with torch.no_grad():
      model.linear.weight -= LR * model.linear.weight.grad
      model.linear.bias -= LR * model.linear.bias.grad


# zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.5910000801086426
Epoch: 2, Loss: 0.4595073461532593
Epoch: 3, Loss: 0.38994601368904114
Epoch: 4, Loss: 0.34650522470474243
Epoch: 5, Loss: 0.31623929738998413
Epoch: 6, Loss: 0.29362064599990845
Epoch: 7, Loss: 0.27588650584220886
Epoch: 8, Loss: 0.26149117946624756
Epoch: 9, Loss: 0.2494959831237793
Epoch: 10, Loss: 0.23929458856582642
Epoch: 11, Loss: 0.23047588765621185
Epoch: 12, Loss: 0.2227502316236496
Epoch: 13, Loss: 0.21590682864189148
Epoch: 14, Loss: 0.20978814363479614
Epoch: 15, Loss: 0.2042737752199173
Epoch: 16, Loss: 0.19926977157592773
Epoch: 17, Loss: 0.19470171630382538
Epoch: 18, Loss: 0.1905096024274826
Epoch: 19, Loss: 0.18664461374282837
Epoch: 20, Loss: 0.18306636810302734
Epoch: 21, Loss: 0.17974117398262024
Epoch: 22, Loss: 0.17664070427417755
Epoch: 23, Loss: 0.173740953207016
Epoch: 24, Loss: 0.1710212528705597
Epoch: 25, Loss: 0.16846391558647156
Epoch: 26, Loss: 0.16605356335639954
Epoch: 27, Loss: 0.16377678513526917
Epoch: 28, Loss: 0.

In [85]:
# model evaluation
with torch.no_grad():
  y_pred = model(x_test_tensor.float())
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.509695291519165


## Built in Optimization Function

In [86]:
import torch.nn as nn
LR=0.1
epochs = 35
loss_func = nn.BCELoss() #Binary cross Entropy


class mysimpleNN(nn.Module):

  def __init__(self, input_size):
    super().__init__()
    self.linear = nn.Linear(input_size, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    x = self.linear(x)
    x = self.sigmoid(x)
    return x



In [87]:
model = mysimpleNN(x_train_tensor.shape[1])


optimizer = torch.optim.SGD(model.parameters(), lr=LR)


for epoch in range(epochs):
# Forward Pass
  y_pred = model(x_train_tensor.float())

# loss
  loss = loss_func(y_pred, y_train_tensor.view(-1,1).float())

#backward pass
  loss.backward()

#update weights

  optimizer.step()


# zero gradients
  optimizer.zero_grad()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 1.1349122524261475
Epoch: 2, Loss: 0.7467208504676819
Epoch: 3, Loss: 0.5465003848075867
Epoch: 4, Loss: 0.44592830538749695
Epoch: 5, Loss: 0.3867667019367218
Epoch: 6, Loss: 0.3473558723926544
Epoch: 7, Loss: 0.3188827335834503
Epoch: 8, Loss: 0.297127366065979
Epoch: 9, Loss: 0.27981436252593994
Epoch: 10, Loss: 0.26560673117637634
Epoch: 11, Loss: 0.2536656856536865
Epoch: 12, Loss: 0.2434372752904892
Epoch: 13, Loss: 0.2345401495695114
Epoch: 14, Loss: 0.22670254111289978
Epoch: 15, Loss: 0.2197251170873642
Epoch: 16, Loss: 0.2134581357240677
Epoch: 17, Loss: 0.2077864706516266
Epoch: 18, Loss: 0.20262010395526886
Epoch: 19, Loss: 0.19788745045661926
Epoch: 20, Loss: 0.19353069365024567
Epoch: 21, Loss: 0.1895025223493576
Epoch: 22, Loss: 0.18576383590698242
Epoch: 23, Loss: 0.18228188157081604
Epoch: 24, Loss: 0.17902901768684387
Epoch: 25, Loss: 0.17598164081573486
Epoch: 26, Loss: 0.17311955988407135
Epoch: 27, Loss: 0.1704251915216446
Epoch: 28, Loss: 0.1678833

In [89]:
# model evaluation
with torch.no_grad():
  y_pred = model(x_test_tensor.float())
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5323176383972168
